fix(plat): clang-tidy unused parameter errors
This patch fixes errors of unused parameters, as suggested by the
clang-tidy misc-unused-parameters check:
- plat/host/host_build/src/host_harness.c:21: error: parameter 'addr' is
unused
- plat/host/host_build/src/host_harness.c:26: error: parameter 'addr' is
unused
- plat/host/host_test/src/host_harness.c:38 error: parameter 'addr' is
unused
- plat/host/host_test/src/host_harness.c:43 error: parameter 'addr' is
unused

Signed-off-by: Chuyue Luo <Chuyue.Luo@arm.com>
Change-Id: I19b1cb2ae3624c7b37fa219f86c88abab56589a7