fix(lib): clang-tidy null pointer dereference errors
This patch suppresses errors from the clang-tidy
clang-analyzer-core.NullDereference check:
- lib/realm/include/granule.h:80: error: Access to field 'state' results
in a dereference of a null pointer (loaded from variable 'g')
- lib/realm/include/granule.h:87: error: Access to field 'state' results
in a dereference of a null pointer (loaded from variable 'g')

assert() calls have been added to verify that 'g' cannot be NULL.
However, the clang-tidy check still must be suppressed for these lines
because clang-tidy cannot see assert() calls.

Signed-off-by: Chuyue Luo <Chuyue.Luo@arm.com>
Change-Id: I75d674c0686fb0195d176f730e212cd7c44afb8f